const path = require('path')
const { defineConfig } = require('vite')
import vue from '@vitejs/plugin-vue'

module.exports = defineConfig(() => {
  const rootPath = path.resolve(process.cwd())
  const srcPath = `${rootPath}/src`
  return {
    resolve: {
      alias: {
        '~': rootPath,
        '@': srcPath
      }
    },
    plugins: [vue()], // to process SFC
    build: {
      lib: {
        entry: path.resolve(__dirname, 'src/index.ts'),
        name: 'VueBottomSheet'
      },
      rollupOptions: {
        // external modules won't be bundled into your library
        external: ['vue', 'hammerjs'], // not every external has a global
        output: {
          // disable warning on src/index.ts using both default and named export
          exports: 'named',
          // Provide global variables to use in the UMD build
          // for externalized deps (not useful if 'umd' is not in lib.formats)
          globals: {
            vue: 'Vue'
          }
        }
      },
      emptyOutDir: false // to retain the types folder generated by tsc
    }
  }
})
